<?php

return [
    90000 => [
        'id' => 90000,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => '404',
        'address' => '/404',
        'name' => '*Page not found*',
        'cache' => NULL,
        'template' => NULL,
        'system' => 1,
        'modules' => [
            'modules\\menu\\client\\horizontal_menu',
            'modules\\special_blocks\\client\\bottom_blocks',
            'modules\\special_blocks\\client\\footer_blocks',
            'modules\\breadcrumbs\\client\\breadcrumbs',
            'modules\\pages\\client\\block_404',
            'modules\\pages\\client\\page_helper',
        ],
        'sub_pages' => [],
    ],
    90001 =>
        [
            'id' => 90001,
            'site' => NULL,
            'parent' => NULL,
            'sites_types' => NULL,
            'type' => 'authorisation',
            'address' => '/login',
            'name' => '*Authorisation*',
            'cache' => NULL,
            'template' => NULL,
            'system' => '1',
            'modules' => [
                'modules\\menu\\client\\horizontal_menu',
                'modules\\pages\\client\\sub_pages_tree',
                'modules\\users\\client\\authorisation',
                'modules\\special_blocks\\client\\recommended_blocks',
                'modules\\special_blocks\\client\\side_blocks',
                'modules\\special_blocks\\client\\bottom_blocks',
                'modules\\special_blocks\\client\\footer_blocks',
                'modules\\breadcrumbs\\client\\breadcrumbs',
                'modules\\pages\\client\\page_helper',
            ],
            'sub_pages' => [
                90002 => [
                    'id' => 90002,
                    'site' => NULL,
                    'parent' => 90001,
                    'sites_types' => NULL,
                    'type' => 'registration',
                    'address' => '/registration',
                    'name' => '*Registration*',
                    'cache' => NULL,
                    'template' => NULL,
                    'system' => '1',
                    'modules' => [
                        'modules\\menu\\client\\horizontal_menu',
                        'modules\\pages\\client\\sub_pages_tree',
                        'modules\\users\\client\\registration',
                        'modules\\special_blocks\\client\\recommended_blocks',
                        'modules\\special_blocks\\client\\side_blocks',
                        'modules\\special_blocks\\client\\special_blocks',
                        'modules\\special_blocks\\client\\footer_blocks',
                        'modules\\breadcrumbs\\client\\breadcrumbs',
                        'modules\\pages\\client\\page_helper',
                    ],
                    'sub_pages' => [],
                ],
                90003 => [
                    'id' => 90003,
                    'site' => NULL,
                    'parent' => 90001,
                    'sites_types' => NULL,
                    'type' => 'password_reset',
                    'address' => '/reset',
                    'name' => '*Reset a password*',
                    'cache' => NULL,
                    'template' => NULL,
                    'system' => '1',
                    'modules' => [
                        'modules\\menu\\client\\horizontal_menu',
                        'modules\\pages\\client\\sub_pages_tree',
                        'modules\\users\\client\\reset',
                        'modules\\special_blocks\\client\\recommended_blocks',
                        'modules\\special_blocks\\client\\side_blocks',
                        'modules\\special_blocks\\client\\special_blocks',
                        'modules\\special_blocks\\client\\footer_blocks',
                        'modules\\breadcrumbs\\client\\breadcrumbs',
                        'modules\\pages\\client\\page_helper',
                    ],
                    'sub_pages' => [],
                ],
            ],
        ],
    90004 => [
        'id' => 90004,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'ajax',
        'address' => '/ajax',
        'name' => 'Ajax',
        'cache' => NULL,
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\ajax\\client\\ajax',
        ],
        'sub_pages' => [],
    ],
    90005 => [
        'id' => 90005,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'photo',
        'address' => '/photo',
        'name' => '*Photo*',
        'cache' => '1',
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\photo\\client\\photo',
        ],
        'sub_pages' => [],
    ],
    90006 => [
        'id' => 90006,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'preview',
        'address' => '/preview',
        'name' => '*Preview*',
        'cache' => '1',
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\photo\\client\\preview',
        ],
        'sub_pages' => [],
    ],
    90007 => [
        'id' => 90007,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'captcha',
        'address' => '/captcha',
        'name' => '*Captcha*',
        'cache' => NULL,
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\captcha\\client\\captcha',
        ],
        'sub_pages' => [],
    ],
    90008 => [
        'id' => 90008,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'cron',
        'address' => '/cron',
        'name' => '*Cron script*',
        'cache' => NULL,
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\cron\\client\\cron',
        ],
        'sub_pages' => [],
    ],
    90009 => [
        'id' => 90009,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'social_action',
        'address' => '/social',
        'name' => '*Social action*',
        'cache' => NULL,
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\users\\client\\social_action',
        ],
        'sub_pages' => [],
    ],
    90010 => [
        'id' => 90010,
        'site' => NULL,
        'parent' => NULL,
        'sites_types' => NULL,
        'type' => 'sitemap',
        'address' => '/sitemap.xml',
        'name' => 'sitemap.xml',
        'cache' => NULL,
        'template' => NULL,
        'system' => '1',
        'modules' => [
            'modules\\seo\\client\\sitemap',
        ],
        'sub_pages' => [],
    ],
    90011 =>
        [
            'id' => 90011,
            'site' => NULL,
            'parent' => NULL,
            'sites_types' => NULL,
            'type' => 'cabinet',
            'address' => '/cabinet',
            'name' => '*Personal cabinet*',
            'cache' => NULL,
            'template' => NULL,
            'system' => '1',
            'modules' => [
                'modules\\menu\\client\\horizontal_menu',
                'modules\\pages\\client\\sub_pages_tree',
                'modules\\users\\client\\cabinet',
                'modules\\special_blocks\\client\\bottom_blocks',
                'modules\\special_blocks\\client\\footer_blocks',
                'modules\\breadcrumbs\\client\\breadcrumbs',
                'modules\\pages\\client\\page_helper',
            ],
            'sub_pages' => [
                90012 => [
                    'id' => 90012,
                    'site' => NULL,
                    'parent' => 90011,
                    'sites_types' => NULL,
                    'type' => 'cabinet',
                    'address' => '/settings',
                    'name' => '*Profile settings*',
                    'cache' => NULL,
                    'template' => NULL,
                    'system' => '1',
                    'modules' => [
                        'modules\\menu\\client\\horizontal_menu',
                        'modules\\pages\\client\\sub_pages_tree',
                        'modules\\users\\client\\cabinet',
                        'modules\\special_blocks\\client\\special_blocks',
                        'modules\\special_blocks\\client\\footer_blocks',
                        'modules\\breadcrumbs\\client\\breadcrumbs',
                        'modules\\pages\\client\\page_helper',
                    ],
                    'sub_pages' => [],
                ],
                90013 => [
                    'id' => 90013,
                    'site' => NULL,
                    'parent' => 90011,
                    'sites_types' => NULL,
                    'type' => 'cabinet',
                    'address' => '/wishlist',
                    'name' => '*Wishlist*',
                    'cache' => NULL,
                    'template' => NULL,
                    'system' => '1',
                    'modules' => [
                        'modules\\menu\\client\\horizontal_menu',
                        'modules\\pages\\client\\sub_pages_tree',
                        'modules\\users\\client\\cabinet',
                        'modules\\special_blocks\\client\\bottom_blocks',
                        'modules\\special_blocks\\client\\footer_blocks',
                        'modules\\breadcrumbs\\client\\breadcrumbs',
                        'modules\\pages\\client\\page_helper',
                    ],
                    'sub_pages' => [],
                ],
            ],
        ],
];
